name = "Glossaries"
uuid = "8f48dd54-e453-4cdc-9500-53b96149560b"
version = "0.1.0"
authors = ["Ronny Bergmann <git@ronnybergmann.net>"]

[compat]
julia = "1.10"

[workspace]
projects = ["test", "docs", "tutorials"]