name: Check Changelog
on:
  pull_request:

jobs:
  Check-News:
    name: Check News have been updated on PR
    runs-on: ubuntu-latest
    steps:
      - uses: tarides/changelog-check-action@v3
        with:
          changelog: NEWS.md